[theme]

# The preset Streamlit theme that your custom theme inherits from.
base = "dark"

# Primary accent color for interactive elements.
primaryColor = "#a78ade"

# Background color for the main content area.
backgroundColor = "#222222"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#53466F"

font = "monospace"
